version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - ./containers/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    command: -f /etc/logstash/conf.d/
    volumes:
      # mount config logstash files to container
      - ./containers/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./containers/logstash/auth-logs.conf:/etc/logstash/conf.d/auth-logs.conf
      # mount logs file to container
      - /home/tinhnx/backend/logs:/home/logs
      - /home/tinhnx/backend-auth/logs:/home/logs/auth
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    volumes:
      - ./containers/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
